# Generated by Django 5.2.8 on 2025-11-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('consumer', 'Consumer'), ('supplier', 'Supplier'), ('admin', 'Admin')], default='supplier', max_length=20),
        ),
    ]
